services:
  db: # Database server
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    networks:
      - todolist-mysql-phpmyadmin
    secrets:
      - db_root_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$(cat /run/secrets/db_root_password)"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  phpmyadmin: # UI for database server
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    networks:
      - todolist-mysql-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
  backend: # Backend server
    build:
      context: backend
    networks:
      - todolist-mysql-phpmyadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
        restart: true
    secrets:
      - db_root_password
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json
        - action: rebuild
          path: ./backend/Dockerfile
  frontend: # Frontend server
    build:
      context: frontend
    ports:
      - 5173:5173
    networks:
      - todolist-mysql-phpmyadmin
    restart: unless-stopped
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend/vite
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/Dockerfile

networks:
  todolist-mysql-phpmyadmin:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt