services:
  db: # Database server
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - todolist-mysql-phpmyadmin
    restart: unless-stopped
  phpmyadmin: # UI for database server
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    networks:
      - todolist-mysql-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
  backend:
    build:
      context: backend
    networks:
      - todolist-mysql-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json
        - action: rebuild
          path: ./backend/Dockerfile

networks:
  todolist-mysql-phpmyadmin:
    driver: bridge
