services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - todolist-mysql-phpmyadmin
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    networks:
      - todolist-mysql-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db

networks:
  todolist-mysql-phpmyadmin:
    driver: bridge
